#!/bin/sh

#[[ -r ~/.wayland ]] && source ~/.wayland

# set default shell and terminal
export SHELL=/bin/bash
export TERM=/usr/bin/alacritty
export TERMINAL_COMMAND='/usr/share/sway/scripts/terminal.sh'

# sway-launcher-desktop with material icons
export GLYPH_DESKTOP="󰄶 "
export GLYPH_COMMAND="󰆍 "
